import type { ImportedTemplateConfig } from "./types";

/**
 * 31 more templates from reactive-resume (10), resumake.io v2 (9), rendercv
 * (9) and open-resume (3). Layout/typography faithfully reflect each source:
 * - reactive-resume templates are named after Pokémon and share a
 *   sidebar/two-column + accent-color design language.
 * - resumake templates map to its LaTeX document classes (article,
 *   awesome-cv, deedy-resume, jakes-resume, moderncv, mcdowellcv).
 * - rendercv themes come from its design YAMLs (serif/sans families, full-line
 *   section rules, centered Harvard header, etc.).
 * - open-resume is a single clean layout offered in several accent colors.
 */
export const COMMUNITY_TEMPLATES: ImportedTemplateConfig[] = [
  // ── Reactive Resume (10) ──────────────────────────────────────────────
  {
    id: "rr-azurill",
    name: "Azurill",
    source: "reactive-resume",
    description: "Reactive Resume's signature: a clean two-column layout with a light sidebar, blue accent and a serif body. Balanced, readable, and fast to scan.",
    tags: ["two-column", "modern", "professional"],
    atsScore: 93,
    header: "standard",
    section: "underline",
    skills: "chips",
    theme: { primary: "#0084d1", text: "#1f2937", muted: "#64748b", sidebar: "#f1f5f9", sidebarText: "#1f2937" },
    typography: { fontFamily: "IBM Plex Serif", headingFamily: "Fira Sans Condensed", nameFamily: "IBM Plex Serif", fontSize: 9.6, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "left", sidebarWidth: 0.32, showPhoto: true, photoShape: "circle", icons: true, sectionGap: 12, itemGap: 7 },
  },
  {
    id: "rr-bronzor",
    name: "Bronzor",
    source: "reactive-resume",
    description: "A calm, minimal single-column with a bronze accent bar and generous whitespace. Clean lines, muted palette.",
    tags: ["single-column", "minimal", "ats-safe"],
    atsScore: 95,
    header: "standard",
    section: "bar",
    skills: "inline",
    theme: { primary: "#b45309", text: "#27272a", muted: "#78716c" },
    typography: { fontFamily: "IBM Plex Sans", headingFamily: "IBM Plex Sans", nameFamily: "IBM Plex Sans", fontSize: 9.7, lineHeight: 1.45, letterSpacing: 0, headingScale: 1.45, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 13, itemGap: 6 },
  },
  {
    id: "rr-ditgar",
    name: "Ditgar",
    source: "reactive-resume",
    description: "Bold editorial single-column with a deep ink palette and strong serif headings. Confident and structured.",
    tags: ["single-column", "executive", "premium"],
    atsScore: 92,
    header: "split",
    section: "rule-after",
    skills: "grouped-chips",
    theme: { primary: "#1e293b", text: "#0f172a", muted: "#64748b" },
    typography: { fontFamily: "Source Sans 3", headingFamily: "Source Serif 4", nameFamily: "Source Serif 4", fontSize: 9.8, lineHeight: 1.42, letterSpacing: 0, headingScale: 1.6, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 12, itemGap: 7 },
  },
  {
    id: "rr-ditto",
    name: "Ditto",
    source: "reactive-resume",
    description: "A soft, neutral layout with a purple accent — adaptable to any field. Clean single-column structure.",
    tags: ["single-column", "modern", "professional"],
    atsScore: 94,
    header: "standard",
    section: "underline",
    skills: "inline",
    theme: { primary: "#7c3aed", text: "#1e1b2e", muted: "#6b7280" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.7, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 12, itemGap: 7 },
  },
  {
    id: "rr-glalie",
    name: "Glalie",
    source: "reactive-resume",
    description: "Cool slate-blue single-column with a crisp top border. Clean, technical, and easy on the eyes.",
    tags: ["single-column", "modern", "technical"],
    atsScore: 94,
    header: "standard",
    section: "rule-after",
    skills: "inline",
    theme: { primary: "#0284c7", text: "#0f172a", muted: "#64748b" },
    typography: { fontFamily: "IBM Plex Sans", headingFamily: "IBM Plex Sans", nameFamily: "IBM Plex Sans", fontSize: 9.7, lineHeight: 1.42, letterSpacing: 0, headingScale: 1.45, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 12, itemGap: 7 },
  },
  {
    id: "rr-kakuna",
    name: "Kakuna",
    source: "reactive-resume",
    description: "Warm amber two-column with a tinted sidebar and pill skills. Approachable and distinct.",
    tags: ["two-column", "modern", "creative"],
    atsScore: 91,
    header: "standard",
    section: "underline",
    skills: "chips",
    theme: { primary: "#d97706", text: "#292524", muted: "#78716c", sidebar: "#fffbeb", sidebarText: "#78350f" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.6, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.45, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "left", sidebarWidth: 0.33, showPhoto: true, photoShape: "circle", sectionGap: 12, itemGap: 7 },
  },
  {
    id: "rr-lapras",
    name: "Lapras",
    source: "reactive-resume",
    description: "A large-name, ice-blue single column with soft card sections. Spacious and modern.",
    tags: ["single-column", "modern", "premium"],
    atsScore: 92,
    header: "centered",
    section: "plain",
    skills: "chips",
    theme: { primary: "#0ea5e9", text: "#1e293b", muted: "#64748b" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.8, lineHeight: 1.45, letterSpacing: 0, headingScale: 1.6, uppercaseHeadings: false },
    layout: { columns: 1, sectionGap: 13, itemGap: 8 },
  },
  {
    id: "rr-meowth",
    name: "Meowth",
    source: "reactive-resume",
    description: "Two-column with a warm gold accent and a light sidebar. A confident, distinctive take.",
    tags: ["two-column", "modern", "creative"],
    atsScore: 91,
    header: "standard",
    section: "bar",
    skills: "chips",
    theme: { primary: "#f59e0b", text: "#292524", muted: "#78716c", sidebar: "#fffbeb", sidebarText: "#78350f" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.6, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.45, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "right", sidebarWidth: 0.33, showPhoto: true, photoShape: "rounded", sectionGap: 12, itemGap: 7 },
  },
  {
    id: "rr-rhyhorn",
    name: "Rhyhorn",
    source: "reactive-resume",
    description: "Grounded terracotta single-column with sturdy serif headings. Reliable and professional.",
    tags: ["single-column", "executive", "classic"],
    atsScore: 94,
    header: "split",
    section: "underline",
    skills: "inline",
    theme: { primary: "#9a3412", text: "#1c1917", muted: "#78716c" },
    typography: { fontFamily: "Source Sans 3", headingFamily: "Source Serif 4", nameFamily: "Source Serif 4", fontSize: 9.8, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.55, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 12, itemGap: 7 },
  },
  {
    id: "rr-scizor",
    name: "Scizor",
    source: "reactive-resume",
    description: "Sharp red single-column with a crisp top accent. Precise, technical, and clean.",
    tags: ["single-column", "modern", "technical"],
    atsScore: 94,
    header: "standard",
    section: "bar",
    skills: "inline",
    theme: { primary: "#dc2626", text: "#1f2937", muted: "#6b7280" },
    typography: { fontFamily: "IBM Plex Sans", headingFamily: "IBM Plex Sans", nameFamily: "IBM Plex Sans", fontSize: 9.6, lineHeight: 1.42, letterSpacing: 0, headingScale: 1.45, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 12, itemGap: 6 },
  },

  // ── Resumake.io v2 (9) ────────────────────────────────────────────────
  {
    id: "rm-article",
    name: "Resumake Plain",
    source: "resumake",
    description: "A plain LaTeX article resume: centered small-caps name, dotted separators, classic ruled sections. The timeless default.",
    tags: ["ats-safe", "single-column", "classic"],
    atsScore: 97,
    header: "centered",
    section: "underline",
    skills: "inline",
    theme: { primary: "#111111", text: "#1a1a1a", muted: "#525252" },
    typography: { fontFamily: "Latin Modern Roman", headingFamily: "Latin Modern Roman", nameFamily: "Latin Modern Roman", fontSize: 10, lineHeight: 1.3, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 10, itemGap: 6 },
  },
  {
    id: "rm-awesome-cv",
    name: "Awesome CV",
    source: "resumake",
    description: "Resumake's AwesomeCV port: a bold two-column with a colored left rail, uppercase name, and icon-driven sections.",
    tags: ["two-column", "modern", "creative"],
    atsScore: 91,
    header: "standard",
    section: "plain",
    skills: "chips",
    theme: { primary: "#e11d48", text: "#1f2937", muted: "#6b7280", sidebar: "#111827", sidebarText: "#f9fafb" },
    typography: { fontFamily: "Fira Sans", headingFamily: "Fira Sans", nameFamily: "Fira Sans", fontSize: 9.4, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "left", sidebarWidth: 0.34, showPhoto: true, photoShape: "square", icons: true, sectionGap: 11, itemGap: 6 },
  },
  {
    id: "rm-deedy",
    name: "Deedy Classic",
    source: "resumake",
    description: "The famous Deedy layout: clean serif, two-column with a left sidebar, uppercase section rules and a single accent.",
    tags: ["two-column", "classic", "premium"],
    atsScore: 93,
    header: "standard",
    section: "rule-after",
    skills: "inline",
    theme: { primary: "#b03a2e", text: "#26211d", muted: "#6b6256", sidebar: "#faf7f2", sidebarText: "#3f372e" },
    typography: { fontFamily: "Lato", headingFamily: "Lato", nameFamily: "Lato", fontSize: 9.4, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.7, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "left", sidebarWidth: 0.3, sectionGap: 10, itemGap: 6 },
  },
  {
    id: "rm-jakes-resume",
    name: "Jake's Resume",
    source: "resumake",
    description: "The legendary Jake's Resume single column: serif, bold name, small-caps headers. Software engineers' favorite.",
    tags: ["ats-safe", "single-column", "technical", "classic"],
    atsScore: 97,
    header: "centered",
    section: "underline",
    skills: "inline",
    theme: { primary: "#111111", text: "#1a1a1a", muted: "#444444" },
    typography: { fontFamily: "Source Serif 4", headingFamily: "Source Serif 4", nameFamily: "Source Serif 4", fontSize: 10, lineHeight: 1.3, letterSpacing: 0, headingScale: 1.6, uppercaseHeadings: false },
    layout: { columns: 1, sectionGap: 9, itemGap: 5 },
  },
  {
    id: "rm-moderncv",
    name: "ModernCV",
    source: "resumake",
    description: "ModernCV's structured single column: uppercase name band, tinted section bars, and tight entries.",
    tags: ["single-column", "modern", "professional"],
    atsScore: 94,
    header: "standard",
    section: "bar",
    skills: "inline",
    theme: { primary: "#0e7490", text: "#1f2937", muted: "#64748b" },
    typography: { fontFamily: "Lato", headingFamily: "Lato", nameFamily: "Lato", fontSize: 9.5, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.4, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 11, itemGap: 6 },
  },
  {
    id: "rm-mcdowell",
    name: "McDowell",
    source: "resumake",
    description: "McDowellCV's clean professional layout: navy accent, ruled headings, right-aligned dates. Recruiter-tested.",
    tags: ["ats-safe", "single-column", "professional"],
    atsScore: 96,
    header: "standard",
    section: "underline",
    skills: "inline",
    theme: { primary: "#1e3a8a", text: "#1f2937", muted: "#6b7280" },
    typography: { fontFamily: "Roboto", headingFamily: "Roboto", nameFamily: "Roboto", fontSize: 9.6, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 11, itemGap: 6 },
  },
  {
    id: "rm-article-serif",
    name: "Resumake Serif",
    source: "resumake",
    description: "A classic serif article resume with centered name and generous line spacing. Quiet, formal, timeless.",
    tags: ["ats-safe", "single-column", "classic"],
    atsScore: 96,
    header: "centered",
    section: "rule-after",
    skills: "inline",
    theme: { primary: "#1a1a1a", text: "#1a1a1a", muted: "#555555" },
    typography: { fontFamily: "EB Garamond", headingFamily: "EB Garamond", nameFamily: "EB Garamond", fontSize: 10, lineHeight: 1.35, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 11, itemGap: 6 },
  },
  {
    id: "rm-article-tech",
    name: "Resumake Tech",
    source: "resumake",
    description: "A compact article variant tuned for engineers: dense entries, mono accent, and clean rule headers.",
    tags: ["ats-safe", "single-column", "technical"],
    atsScore: 96,
    header: "split",
    section: "bar",
    skills: "inline",
    theme: { primary: "#0f766e", text: "#111827", muted: "#6b7280" },
    typography: { fontFamily: "IBM Plex Sans", headingFamily: "IBM Plex Mono", nameFamily: "IBM Plex Mono", fontSize: 9.4, lineHeight: 1.35, letterSpacing: 0, headingScale: 1.4, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 10, itemGap: 5 },
  },
  {
    id: "rm-article-minimal",
    name: "Resumake Minimal",
    source: "resumake",
    description: "The lightest resumake article: thin rules, muted labels, maximum whitespace. Nothing but content.",
    tags: ["ats-safe", "single-column", "minimal"],
    atsScore: 95,
    header: "standard",
    section: "plain",
    skills: "inline",
    theme: { primary: "#374151", text: "#27272a", muted: "#71717a" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.7, lineHeight: 1.5, letterSpacing: 0, headingScale: 1.4, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 13, itemGap: 6 },
  },

  // ── RenderCV (9) ──────────────────────────────────────────────────────
  {
    id: "rc-classic",
    name: "RenderCV Classic",
    source: "rendercv",
    description: "RenderCV's original classic theme: serif body, centered name, full-line section rules, right-aligned details. Academic-grade.",
    tags: ["ats-safe", "single-column", "classic"],
    atsScore: 96,
    header: "centered",
    section: "rule-after",
    skills: "inline",
    theme: { primary: "#1a1a1a", text: "#1a1a1a", muted: "#4b5563" },
    typography: { fontFamily: "Latin Modern Roman", headingFamily: "Latin Modern Roman", nameFamily: "Latin Modern Roman", fontSize: 9.9, lineHeight: 1.34, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 10, itemGap: 6 },
  },
  {
    id: "rc-engineeringclassic",
    name: "Engineering Classic",
    source: "rendercv",
    description: "RenderCV's engineering-classic theme: Raleway sans-serif, left-aligned name, full-line section rules. Engineer-friendly.",
    tags: ["ats-safe", "single-column", "technical"],
    atsScore: 96,
    header: "standard",
    section: "rule-after",
    skills: "inline",
    theme: { primary: "#111827", text: "#111827", muted: "#6b7280" },
    typography: { fontFamily: "Raleway", headingFamily: "Raleway", nameFamily: "Raleway", fontSize: 9.7, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.45, uppercaseHeadings: false },
    layout: { columns: 1, sectionGap: 10, itemGap: 6 },
  },
  {
    id: "rc-engineeringresumes",
    name: "Engineering Resumes",
    source: "rendercv",
    description: "The beloved engineering-resumes theme: serif, pipe-separated contact, full-line rules. The all-time GitHub favorite.",
    tags: ["ats-safe", "single-column", "technical", "classic"],
    atsScore: 97,
    header: "standard",
    section: "underline",
    skills: "inline",
    theme: { primary: "#111111", text: "#111111", muted: "#525252" },
    typography: { fontFamily: "XCharter", headingFamily: "XCharter", nameFamily: "XCharter", fontSize: 9.8, lineHeight: 1.34, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: false },
    layout: { columns: 1, sectionGap: 10, itemGap: 6 },
  },
  {
    id: "rc-harvard",
    name: "RenderCV Harvard",
    source: "rendercv",
    description: "RenderCV's Harvard theme: pure black on white, serif, centered header with a full-width rule. Maximally formal.",
    tags: ["ats-safe", "single-column", "classic", "executive"],
    atsScore: 97,
    header: "centered",
    section: "rule-after",
    skills: "inline",
    theme: { primary: "#000000", text: "#000000", muted: "#3f3f3f" },
    typography: { fontFamily: "XCharter", headingFamily: "XCharter", nameFamily: "XCharter", fontSize: 10, lineHeight: 1.32, letterSpacing: 0, headingScale: 1.55, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 10, itemGap: 6 },
  },
  {
    id: "rc-sb2nov",
    name: "SB2Nov",
    source: "rendercv",
    description: "SB2Nov's famous resume theme: Computer Modern serif, underlined links, full-line section rules. The template everyone starts with.",
    tags: ["ats-safe", "single-column", "classic", "technical"],
    atsScore: 97,
    header: "standard",
    section: "rule-after",
    skills: "inline",
    theme: { primary: "#111111", text: "#111111", muted: "#525252" },
    typography: { fontFamily: "Computer Modern", headingFamily: "Computer Modern", nameFamily: "Computer Modern", fontSize: 9.9, lineHeight: 1.32, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: false },
    layout: { columns: 1, sectionGap: 10, itemGap: 6 },
  },
  {
    id: "rc-ember",
    name: "Ember",
    source: "rendercv",
    description: "RenderCV's Ember theme: warm Gentium serif name over Ubuntu body with justified text. Cozy and elegant.",
    tags: ["single-column", "elegant", "premium"],
    atsScore: 92,
    header: "centered",
    section: "plain",
    skills: "inline",
    theme: { primary: "#9a3412", text: "#292524", muted: "#78716c" },
    typography: { fontFamily: "Ubuntu", headingFamily: "Gentium Book Plus", nameFamily: "Gentium Book Plus", fontSize: 9.8, lineHeight: 1.44, letterSpacing: 0, headingScale: 1.6, uppercaseHeadings: false },
    layout: { columns: 1, sectionGap: 12, itemGap: 7 },
  },
  {
    id: "rc-ink",
    name: "Ink",
    source: "rendercv",
    description: "RenderCV's Ink theme: EB Garamond throughout, justified text, no icons. Editorially serene.",
    tags: ["single-column", "elegant", "classic"],
    atsScore: 95,
    header: "centered",
    section: "rule-after",
    skills: "inline",
    theme: { primary: "#1a1a1a", text: "#1a1a1a", muted: "#555555" },
    typography: { fontFamily: "EB Garamond", headingFamily: "EB Garamond", nameFamily: "EB Garamond", fontSize: 10, lineHeight: 1.36, letterSpacing: 0, headingScale: 1.55, uppercaseHeadings: false },
    layout: { columns: 1, sectionGap: 11, itemGap: 6 },
  },
  {
    id: "rc-moderncv",
    name: "RenderCV ModernCV",
    source: "rendercv",
    description: "RenderCV's ModernCV theme: Fontin serif with a left-aligned header, photo slot, and clean section bars.",
    tags: ["single-column", "modern", "classic"],
    atsScore: 94,
    header: "split",
    section: "bar",
    skills: "chips",
    theme: { primary: "#1e3a8a", text: "#1f2937", muted: "#6b7280" },
    typography: { fontFamily: "Fontin", headingFamily: "Fontin", nameFamily: "Fontin", fontSize: 9.7, lineHeight: 1.38, letterSpacing: 0, headingScale: 1.45, uppercaseHeadings: true },
    layout: { columns: 1, showPhoto: true, photoShape: "rounded", photoSize: "m", sectionGap: 11, itemGap: 6 },
  },
  {
    id: "rc-opal",
    name: "RenderCV Opal",
    source: "rendercv",
    description: "RenderCV's Opal theme: Lato sans with generous margins and a clean, friendly header. Simple and effective.",
    tags: ["ats-safe", "single-column", "modern", "minimal"],
    atsScore: 95,
    header: "standard",
    section: "plain",
    skills: "inline",
    theme: { primary: "#0f766e", text: "#1f2937", muted: "#6b7280" },
    typography: { fontFamily: "Lato", headingFamily: "Lato", nameFamily: "Lato", fontSize: 9.7, lineHeight: 1.45, letterSpacing: 0, headingScale: 1.45, uppercaseHeadings: false },
    layout: { columns: 1, sectionGap: 13, itemGap: 7 },
  },

  // ── Open Resume (3) ───────────────────────────────────────────────────
  {
    id: "or-blue",
    name: "Open Resume Blue",
    source: "open-resume",
    description: "Open Resume's clean single column in its signature sky blue — bold name, thin rules, tight, modern.",
    tags: ["ats-safe", "single-column", "modern"],
    atsScore: 95,
    header: "standard",
    section: "underline",
    skills: "chips",
    theme: { primary: "#0ea5e9", text: "#1f2937", muted: "#6b7280" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.7, lineHeight: 1.42, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 12, itemGap: 6 },
  },
  {
    id: "or-green",
    name: "Open Resume Green",
    source: "open-resume",
    description: "Open Resume's clean single column in a fresh emerald accent. Crisp and recruiter-friendly.",
    tags: ["ats-safe", "single-column", "modern"],
    atsScore: 95,
    header: "standard",
    section: "underline",
    skills: "chips",
    theme: { primary: "#22c55e", text: "#1f2937", muted: "#6b7280" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.7, lineHeight: 1.42, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 12, itemGap: 6 },
  },
  {
    id: "or-indigo",
    name: "Open Resume Indigo",
    source: "open-resume",
    description: "Open Resume's clean single column in a confident indigo. Professional, modern, universally readable.",
    tags: ["ats-safe", "single-column", "modern"],
    atsScore: 95,
    header: "standard",
    section: "underline",
    skills: "chips",
    theme: { primary: "#6366f1", text: "#1f2937", muted: "#6b7280" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.7, lineHeight: 1.42, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 12, itemGap: 6 },
  },
];
