import type { ImportedTemplateConfig } from "./types";

/**
 * 52 templates transcribed from CVAurum's `src/templates/registry.ts`
 * (https://github.com/akhil-dara/CVAurum). Each entry's theme / typography /
 * layout defaults are preserved verbatim from the source registry; the
 * generic renderer consumes these configs directly.
 */
export const CVAURUM_TEMPLATES: ImportedTemplateConfig[] = [
  {
    id: "cv-aurum-clarity",
    name: "Clarity",
    source: "cv-aurum",
    description: "The modern professional standard: heavy ruled headings, dotted entry dividers, accent-blue employers, a right rail on white, score blocks for education, and underlined skill tags. Rich, structured, endlessly scannable.",
    tags: ["two-column", "modern", "premium"],
    atsScore: 94,
    header: "standard",
    section: "underline",
    skills: "chips",
    sectionIcons: false,
    theme: { primary: "#2b7fd4", text: "#1e2532", muted: "#6a7686", sidebar: "#ffffff", sidebarText: "#1e2532" },
    typography: { fontFamily: "Lato", headingFamily: "Poppins", nameFamily: "Poppins", fontSize: 9.6, lineHeight: 1.38, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "right", sidebarWidth: 0.32, showPhoto: true, photoShape: "rounded" },
  },
  {
    id: "cv-aurum-obsidian",
    name: "Obsidian",
    source: "cv-aurum",
    description: "Layered blacks, tactile entry cards, and tracked gold labels — a dark, luxury-fintech aesthetic. Every word stays selectable text, so the drama costs nothing in parsing.",
    tags: ["single-column", "creative", "premium"],
    atsScore: 90,
    header: "standard",
    section: "plain",
    skills: "grouped-chips",
    sectionIcons: false,
    theme: { primary: "#e3bd6d", text: "#eceef2", muted: "#98a1b0", background: "#0d0e12", sidebar: "#0a0b0e", sidebarText: "#eceef2" },
    typography: { fontFamily: "Inter", headingFamily: "Archivo", nameFamily: "Archivo", fontSize: 9.7, lineHeight: 1.44, letterSpacing: 0, headingScale: 1.6, uppercaseHeadings: true },
    layout: { columns: 1, icons: false, showPhoto: false, sectionGap: 13, itemGap: 8 },
  },
  {
    id: "cv-aurum-onyx-noir",
    name: "Onyx Noir",
    source: "cv-aurum",
    description: "A full-bleed charcoal résumé with an electric-teal accent and crisp white type — the dark, high-contrast look that turns heads. Selectable text throughout, so it still reads clean for ATS.",
    tags: ["single-column", "creative", "premium"],
    atsScore: 90,
    header: "standard",
    section: "rule-after",
    skills: "grouped-chips",
    sectionIcons: false,
    theme: { primary: "#2dd4bf", text: "#e8ebef", muted: "#98a1ad", background: "#15181e", sidebar: "#0c0e12", sidebarText: "#e8ebef" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.8, lineHeight: 1.42, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 1, icons: true, showPhoto: false, sectionGap: 12, itemGap: 7 },
  },
  {
    id: "cv-aurum-cascade",
    name: "Cascade",
    source: "cv-aurum",
    description: "A confident two-column with a deep-teal sidebar carrying your photo, skills and languages, and a clean white main column for experience. Bold, colorful, instantly modern.",
    tags: ["two-column", "modern", "premium", "photo"],
    atsScore: 91,
    header: "standard",
    section: "underline",
    skills: "chips",
    sectionIcons: false,
    theme: { primary: "#0d9488", text: "#1f2933", muted: "#5b6776", sidebar: "#0d9488", sidebarText: "#ecfeff" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.7, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true, },
    layout: { columns: 2, sidebar: "left", sidebarWidth: 0.34, showPhoto: true, photoShape: "circle" },
  },
  {
    id: "cv-aurum-sapphire",
    name: "Sapphire",
    source: "cv-aurum",
    description: "Corporate two-column with a deep-navy sidebar, a squared photo, and dot-meter skills — the polished, recruiter-ready look that dominates modern builders.",
    tags: ["two-column", "modern", "premium", "photo"],
    atsScore: 92,
    header: "standard",
    section: "bar",
    skills: "chips",
    sectionIcons: false,
    theme: { primary: "#1e3a8a", text: "#1b2330", muted: "#54607a", sidebar: "#1e293b", sidebarText: "#e2e8f0" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.7, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "left", sidebarWidth: 0.33, showPhoto: true, photoShape: "square" },
  },
  {
    id: "cv-aurum-garnet",
    name: "Garnet",
    source: "cv-aurum",
    description: "A warm, editorial two-column with a burgundy sidebar on the right, a rounded photo, and bar-meter skills — distinctive and premium without shouting.",
    tags: ["two-column", "creative", "premium", "photo"],
    atsScore: 90,
    header: "standard",
    section: "underline",
    skills: "chips",
    sectionIcons: false,
    theme: { primary: "#9f1239", text: "#2a2024", muted: "#6e5b60", sidebar: "#7f1d1d", sidebarText: "#fde8e8" },
    typography: { fontFamily: "Lato", headingFamily: "Lato", nameFamily: "Lato", fontSize: 9.7, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "right", sidebarWidth: 0.33, showPhoto: true, photoShape: "rounded" },
  },
  {
    id: "cv-aurum-initials",
    name: "Initials",
    source: "cv-aurum",
    description: "Monogram-led two-column: your initials in a diamond badge atop a deep sidebar, with a crisp white main column. Distinctive, confident, unmistakably modern.",
    tags: ["two-column", "modern", "premium"],
    atsScore: 91,
    header: "standard",
    section: "bar",
    skills: "chips",
    sectionIcons: false,
    theme: { primary: "#0ea5e9", text: "#1b2330", muted: "#54607a", sidebar: "#0f172a", sidebarText: "#e2e8f0" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.7, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "left", sidebarWidth: 0.33, monogram: true, photoShape: "diamond", showPhoto: false },
  },
  {
    id: "cv-aurum-emblem",
    name: "Emblem",
    source: "cv-aurum",
    description: "A centered single-column with a circular monogram crest over a tracked serif name — formal, balanced, and ruthlessly ATS-clean.",
    tags: ["ats-safe", "single-column", "classic", "premium"],
    atsScore: 96,
    header: "centered",
    section: "underline",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#334155", text: "#1b2230", muted: "#5b6776" },
    typography: { fontFamily: "Source Sans 3", headingFamily: "Source Serif 4", nameFamily: "Source Serif 4", fontSize: 10, lineHeight: 1.34, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 1, icons: false, monogram: true, photoShape: "circle", showPhoto: false },
  },
  {
    id: "cv-aurum-verde",
    name: "Verde",
    source: "cv-aurum",
    description: "Fresh two-column with a forest-green sidebar, a circular photo, and skill pills — natural, modern, approachable.",
    tags: ["two-column", "modern", "premium", "photo"],
    atsScore: 91,
    header: "standard",
    section: "underline",
    skills: "chips",
    sectionIcons: false,
    theme: { primary: "#15803d", text: "#1f2933", muted: "#5b6776", sidebar: "#166534", sidebarText: "#ecfdf5" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.7, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "left", sidebarWidth: 0.34, showPhoto: true, photoShape: "circle" },
  },
  {
    id: "cv-aurum-onyx-gold",
    name: "Onyx Gold",
    source: "cv-aurum",
    description: "The charcoal résumé in warm gold — the same bold dark canvas with a luxe amber accent. Selectable text, ATS-clean.",
    tags: ["single-column", "creative", "premium"],
    atsScore: 90,
    header: "standard",
    section: "rule-after",
    skills: "grouped-chips",
    sectionIcons: false,
    theme: { primary: "#d4a24e", text: "#ece7df", muted: "#a39a88", background: "#1a1713", sidebar: "#120f0b", sidebarText: "#ece7df" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.8, lineHeight: 1.42, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 1, icons: true, showPhoto: false, sectionGap: 12, itemGap: 7 },
  },
  {
    id: "cv-aurum-pinnacle",
    name: "Pinnacle",
    source: "cv-aurum",
    description: "Executive two-column: a circular monogram over a charcoal sidebar, dot-meter skills, and a clean main column.",
    tags: ["two-column", "modern", "premium"],
    atsScore: 92,
    header: "standard",
    section: "bar",
    skills: "chips",
    sectionIcons: false,
    theme: { primary: "#0f766e", text: "#1b2330", muted: "#54607a", sidebar: "#1f2937", sidebarText: "#e5e7eb" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.7, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "left", sidebarWidth: 0.33, monogram: true, photoShape: "circle", showPhoto: false },
  },
  {
    id: "cv-aurum-crest",
    name: "Crest",
    source: "cv-aurum",
    description: "Traditional single-column with a squared monogram crest, centered serif name, and ruled headings — formal and ATS-perfect.",
    tags: ["ats-safe", "single-column", "classic"],
    atsScore: 96,
    header: "centered",
    section: "underline",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#7c2d12", text: "#1f2937", muted: "#5b6776" },
    typography: { fontFamily: "PT Serif", headingFamily: "PT Serif", nameFamily: "PT Serif", fontSize: 10.2, lineHeight: 1.3, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 1, icons: false, monogram: true, photoShape: "square", showPhoto: false },
  },
  {
    id: "cv-aurum-ribbon",
    name: "Ribbon",
    source: "cv-aurum",
    description: "A bold full-width color banner masthead over a clean single column — striking and modern, every word still selectable.",
    tags: ["single-column", "creative", "premium"],
    atsScore: 89,
    header: "banner",
    section: "rule-after",
    skills: "grouped-chips",
    sectionIcons: false,
    theme: { primary: "#4338ca", text: "#1f2937", muted: "#5b6776" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.8, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 1, icons: true, showPhoto: false, sectionGap: 12, itemGap: 7 },
  },
  {
    id: "cv-aurum-orchid",
    name: "Orchid",
    source: "cv-aurum",
    description: "A refined two-column with a plum sidebar on the right, a rounded photo, and bar-meter skills — distinctive and warm.",
    tags: ["two-column", "creative", "premium", "photo"],
    atsScore: 90,
    header: "standard",
    section: "underline",
    skills: "chips",
    sectionIcons: false,
    theme: { primary: "#7e22ce", text: "#2a2433", muted: "#5f5870", sidebar: "#581c87", sidebarText: "#f5e8ff" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.7, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "right", sidebarWidth: 0.33, showPhoto: true, photoShape: "rounded" },
  },
  {
    id: "cv-aurum-aurum",
    name: "Aurum",
    source: "cv-aurum",
    description: "The signature design: editorial ink layout with a serif name and a hairline gold accent — premium and unmistakably yours, still fully ATS-safe.",
    tags: ["ats-safe", "single-column", "premium", "modern"],
    atsScore: 95,
    header: "standard",
    section: "plain",
    skills: "grouped-chips",
    sectionIcons: false,
    theme: { primary: "#1c1a17", text: "#23211d", muted: "#6b6357" },
    typography: { fontFamily: "Source Sans 3", headingFamily: "Source Sans 3", nameFamily: "Source Serif 4", fontSize: 9.8, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.55, uppercaseHeadings: true },
    layout: { columns: 1, icons: false, sectionGap: 12, itemGap: 7 },
  },
  {
    id: "cv-aurum-aurum-editorial",
    name: "Aurum Editorial",
    source: "cv-aurum",
    description: "Editorial gold: Cormorant serif headings, a small-caps gold name, and a single hairline gold rule under each heading. Magazine-grade and premium.",
    tags: ["ats-safe", "single-column", "premium", "elegant"],
    atsScore: 94,
    header: "centered",
    section: "plain",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#23211d", text: "#23211d", muted: "#6b6357" },
    typography: { fontFamily: "Source Sans 3", headingFamily: "Cormorant Garamond", nameFamily: "Cormorant Garamond", fontSize: 9.9, lineHeight: 1.42, letterSpacing: 0, headingScale: 1.9, uppercaseHeadings: false },
    layout: { columns: 1, icons: false, sectionGap: 12, itemGap: 7 },
  },
  {
    id: "cv-aurum-swiss-aurum",
    name: "Swiss Aurum",
    source: "cv-aurum",
    description: "Swiss-modernist grid: Inter, generous white space, tracked caps labels with a gold tick. Crisp, contemporary, unmistakably premium.",
    tags: ["ats-safe", "single-column", "premium", "modern"],
    atsScore: 95,
    header: "standard",
    section: "plain",
    skills: "grouped-chips",
    sectionIcons: false,
    theme: { primary: "#1a1a1a", text: "#1a1a1a", muted: "#5a5a5a" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.6, lineHeight: 1.5, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 1, icons: false, sectionGap: 15, itemGap: 8 },
  },
  {
    id: "cv-aurum-atelier",
    name: "Atelier",
    source: "cv-aurum",
    description: "Couture editorial: a Playfair serif name over a gold monospace tagline, gold gutter labels, and a single gold accent tick. Jewellery-grade — the one that turns heads.",
    tags: ["single-column", "premium", "elegant"],
    atsScore: 92,
    header: "standard",
    section: "side",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#9a7b16", text: "#22201c", muted: "#6b6457" },
    typography: { fontFamily: "IBM Plex Sans", headingFamily: "IBM Plex Mono", nameFamily: "Playfair Display", fontSize: 9.6, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.8, uppercaseHeadings: true },
    layout: { columns: 1, icons: false, sectionGap: 12, itemGap: 7 },
  },
  {
    id: "cv-aurum-harvard",
    name: "Harvard",
    source: "cv-aurum",
    description: "The classic Harvard format recruiters know: centered serif name, bold uppercase section rules, impeccable structure. Pure black, maximally ATS.",
    tags: ["ats-safe", "single-column", "classic"],
    atsScore: 97,
    header: "centered",
    section: "underline",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#111111", text: "#1a1a1a", muted: "#3f3f3f" },
    typography: { fontFamily: "Source Serif 4", headingFamily: "Source Serif 4", nameFamily: "Source Serif 4", fontSize: 10, lineHeight: 1.32, letterSpacing: 0, headingScale: 1.55, uppercaseHeadings: true },
    layout: { columns: 1, icons: false, sectionGap: 10, itemGap: 6 },
  },
  {
    id: "cv-aurum-garamond",
    name: "Garamond",
    source: "cv-aurum",
    description: "The timeless Garamond résumé recruiters trust — a bold old-style serif name, clean ruled sections, impeccable single-column structure. Classic and ATS-perfect.",
    tags: ["ats-safe", "single-column", "classic", "elegant"],
    atsScore: 97,
    header: "standard",
    section: "underline",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#1a1a1a", text: "#1a1a1a", muted: "#555555" },
    typography: { fontFamily: "EB Garamond", headingFamily: "EB Garamond", nameFamily: "EB Garamond", fontSize: 10.5, lineHeight: 1.3, letterSpacing: 0, headingScale: 1.6, uppercaseHeadings: true },
    layout: { columns: 1, icons: false, sectionGap: 10, itemGap: 6 },
  },
  {
    id: "cv-aurum-aria",
    name: "Aria",
    source: "cv-aurum",
    description: "Clean single-column with a confident accent. The safe, sharp default.",
    tags: ["ats-safe", "single-column", "modern"],
    atsScore: 95,
    header: "standard",
    section: "underline",
    skills: "grouped-chips",
    sectionIcons: false,
    theme: { primary: "#2563eb", text: "#1f2937", muted: "#64748b" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.6, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 1 },
  },
  {
    id: "cv-aurum-oxford",
    name: "Oxford",
    source: "cv-aurum",
    description: "Timeless serif résumé. Conservative, recruiter-friendly, ATS-perfect.",
    tags: ["ats-safe", "single-column", "classic"],
    atsScore: 97,
    header: "centered",
    section: "rule-after",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#1f2937", text: "#1a1a1a", muted: "#52525b" },
    typography: { fontFamily: "PT Serif", headingFamily: "PT Serif", nameFamily: "PT Serif", fontSize: 9.6, lineHeight: 1.42, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: false },
    layout: { columns: 1, icons: false },
  },
  {
    id: "cv-aurum-cambridge",
    name: "Cambridge",
    source: "cv-aurum",
    description: "RenderCV-grade clean layout: Source Sans, navy accent, ruled headings, right-aligned dates. The academic/engineer favorite.",
    tags: ["ats-safe", "single-column", "classic"],
    atsScore: 96,
    header: "centered",
    section: "plain",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#0e4c92", text: "#1a1a1a", muted: "#525c6b" },
    typography: { fontFamily: "Source Sans 3", headingFamily: "Source Sans 3", nameFamily: "Source Sans 3", fontSize: 9.8, lineHeight: 1.34, letterSpacing: 0, headingScale: 1.55, uppercaseHeadings: false },
    layout: { columns: 1, icons: false, sectionGap: 10, itemGap: 6 },
  },
  {
    id: "cv-aurum-vector",
    name: "Vector",
    source: "cv-aurum",
    description: "The beloved single-column tech format (Jake's Resume lineage): small-caps ruled headings, italic roles, ruthless ATS clarity. A favorite for software roles.",
    tags: ["ats-safe", "single-column", "technical", "classic"],
    atsScore: 97,
    header: "centered",
    section: "underline",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#111111", text: "#1a1a1a", muted: "#444444" },
    typography: { fontFamily: "Source Serif 4", headingFamily: "Source Serif 4", nameFamily: "Source Serif 4", fontSize: 10, lineHeight: 1.3, letterSpacing: 0, headingScale: 1.6, uppercaseHeadings: false },
    layout: { columns: 1, icons: false, sectionGap: 9, itemGap: 5 },
  },
  {
    id: "cv-aurum-frost",
    name: "Frost",
    source: "cv-aurum",
    description: "Maximum whitespace, no chrome. Lets the words carry the page.",
    tags: ["ats-safe", "single-column", "minimal"],
    atsScore: 95,
    header: "standard",
    section: "plain",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#0f172a", text: "#27272a", muted: "#71717a" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.6, lineHeight: 1.5, letterSpacing: 0, headingScale: 1.4, uppercaseHeadings: true },
    layout: { columns: 1, icons: false, sectionGap: 13, itemGap: 6 },
  },
  {
    id: "cv-aurum-sterling",
    name: "Sterling",
    source: "cv-aurum",
    description: "Senior, authoritative. Playfair headings over a clean body.",
    tags: ["ats-safe", "single-column", "executive", "elegant"],
    atsScore: 93,
    header: "split",
    section: "underline",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#1e3a5f", text: "#1a202c", muted: "#5a6678" },
    typography: { fontFamily: "Lato", headingFamily: "Playfair Display", nameFamily: "Playfair Display", fontSize: 9.6, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.6, uppercaseHeadings: true },
    layout: { columns: 1 },
  },
  {
    id: "cv-aurum-vertex",
    name: "Vertex",
    source: "cv-aurum",
    description: "A vertical timeline rail threads your experience into a story.",
    tags: ["single-column", "modern", "timeline"],
    atsScore: 92,
    header: "standard",
    section: "bar",
    skills: "grouped-chips",
    sectionIcons: false,
    theme: { primary: "#0ea5e9", text: "#1e293b", muted: "#64748b" },
    typography: { fontFamily: "Rubik", headingFamily: "Rubik", nameFamily: "Rubik", fontSize: 9.6, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 1 },
  },
  {
    id: "cv-aurum-apex",
    name: "Apex",
    source: "cv-aurum",
    description: "Dark sidebar for skills & contact, generous main column for impact.",
    tags: ["two-column", "modern", "technical"],
    atsScore: 93,
    header: "standard",
    section: "underline",
    skills: "bars",
    sectionIcons: false,
    theme: { primary: "#0ea5e9", text: "#1f2937", muted: "#64748b", sidebar: "#0f172a", sidebarText: "#e2e8f0" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.3, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "left", sidebarWidth: 0.33 },
  },
  {
    id: "cv-aurum-prism",
    name: "Prism",
    source: "cv-aurum",
    description: "A bold color sidebar. Confident, contemporary, memorable.",
    tags: ["two-column", "creative", "modern", "photo"],
    atsScore: 91,
    header: "standard",
    section: "underline",
    skills: "dots",
    sectionIcons: false,
    theme: { primary: "#1d4ed8", text: "#1f2937", muted: "#64748b", sidebar: "#1d4ed8", sidebarText: "#eff6ff" },
    typography: { fontFamily: "Montserrat", headingFamily: "Montserrat", nameFamily: "Montserrat", fontSize: 9.3, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.45, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "left", sidebarWidth: 0.34, showPhoto: true, photoShape: "circle" },
  },
  {
    id: "cv-aurum-linen",
    name: "Linen",
    source: "cv-aurum",
    description: "A soft right sidebar keeps the focus on your story, then your skills.",
    tags: ["two-column", "modern", "minimal"],
    atsScore: 93,
    header: "standard",
    section: "plain",
    skills: "chips",
    sectionIcons: false,
    theme: { primary: "#4f46e5", text: "#27272a", muted: "#71717a", sidebar: "#f4f4f8", sidebarText: "#3f3f56" },
    typography: { fontFamily: "Work Sans", headingFamily: "Work Sans", nameFamily: "Work Sans", fontSize: 9.6, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.45, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "right", sidebarWidth: 0.32 },
  },
  {
    id: "cv-aurum-quartz",
    name: "Quartz",
    source: "cv-aurum",
    description: "Dense and efficient. Fits a deep career on a single page.",
    tags: ["ats-safe", "single-column", "compact"],
    atsScore: 95,
    header: "compact",
    section: "rule-after",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#374151", text: "#1f2937", muted: "#6b7280" },
    typography: { fontFamily: "Roboto", headingFamily: "Roboto", nameFamily: "Roboto", fontSize: 8.8, lineHeight: 1.32, letterSpacing: 0, headingScale: 1.35, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 9, itemGap: 5 },
  },
  {
    id: "cv-aurum-lumiere",
    name: "Lumière",
    source: "cv-aurum",
    description: "Refined Garamond with airy spacing. Quietly luxurious.",
    tags: ["single-column", "elegant", "minimal"],
    atsScore: 94,
    header: "centered",
    section: "plain",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#9a7b4f", text: "#2d2a26", muted: "#7a7268" },
    typography: { fontFamily: "EB Garamond", headingFamily: "Cormorant Garamond", nameFamily: "Cormorant Garamond", fontSize: 10.3, lineHeight: 1.42, letterSpacing: 0.01, headingScale: 1.7, uppercaseHeadings: true },
    layout: { columns: 1, icons: false, sectionGap: 11 },
  },
  {
    id: "cv-aurum-editorial",
    name: "Editorial",
    source: "cv-aurum",
    description: "Editorial gutter headings. Magazine-grade structure.",
    tags: ["single-column", "modern", "creative"],
    atsScore: 92,
    header: "standard",
    section: "side",
    skills: "grouped-chips",
    sectionIcons: false,
    theme: { primary: "#e11d48", text: "#27272a", muted: "#71717a" },
    typography: { fontFamily: "DM Sans", headingFamily: "DM Sans", nameFamily: "DM Sans", fontSize: 9.6, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 11 },
  },
  {
    id: "cv-aurum-marquee",
    name: "Marquee",
    source: "cv-aurum",
    description: "A full-width color banner sets a bold, confident tone.",
    tags: ["single-column", "creative", "modern"],
    atsScore: 90,
    header: "banner",
    section: "bar",
    skills: "chips",
    sectionIcons: false,
    theme: { primary: "#7c3aed", text: "#1f2937", muted: "#64748b" },
    typography: { fontFamily: "Poppins", headingFamily: "Poppins", nameFamily: "Poppins", fontSize: 9.3, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.4, uppercaseHeadings: true },
    layout: { columns: 1 },
  },
  {
    id: "cv-aurum-terminal",
    name: "Terminal",
    source: "cv-aurum",
    description: "Monospace headings and skill tags. Built for engineers.",
    tags: ["ats-safe", "single-column", "technical"],
    atsScore: 93,
    header: "standard",
    section: "bar",
    skills: "chips",
    sectionIcons: false,
    theme: { primary: "#059669", text: "#111827", muted: "#6b7280" },
    typography: { fontFamily: "IBM Plex Sans", headingFamily: "IBM Plex Mono", nameFamily: "IBM Plex Mono", fontSize: 9.3, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.4, uppercaseHeadings: false },
    layout: { columns: 1 },
  },
  {
    id: "cv-aurum-nova",
    name: "Nova",
    source: "cv-aurum",
    description: "Vivid sidebar, photo, and rounded tags. Stand out tastefully.",
    tags: ["two-column", "creative", "photo"],
    atsScore: 90,
    header: "banner",
    section: "plain",
    skills: "dots",
    sectionIcons: false,
    theme: { primary: "#8b5cf6", text: "#27272a", muted: "#71717a", sidebar: "#6d28d9", sidebarText: "#f5f3ff" },
    typography: { fontFamily: "Poppins", headingFamily: "Poppins", nameFamily: "Poppins", fontSize: 9.3, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.4, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "left", sidebarWidth: 0.35, showPhoto: true, photoShape: "rounded" },
  },
  {
    id: "cv-aurum-scholar",
    name: "Scholar",
    source: "cv-aurum",
    description: "Academic, Times-set, single column. The gold standard for tradition.",
    tags: ["ats-safe", "single-column", "classic"],
    atsScore: 96,
    header: "centered",
    section: "rule-after",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#3b1f1f", text: "#1a1a1a", muted: "#57534e" },
    typography: { fontFamily: "Tinos", headingFamily: "Tinos", nameFamily: "Tinos", fontSize: 9.8, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.45, uppercaseHeadings: true },
    layout: { columns: 1, icons: false },
  },
  {
    id: "cv-aurum-onyx",
    name: "Onyx",
    source: "cv-aurum",
    description: "Monochrome and architectural. Quiet confidence in black and white.",
    tags: ["ats-safe", "single-column", "minimal", "modern"],
    atsScore: 94,
    header: "split",
    section: "rule-after",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#18181b", text: "#18181b", muted: "#71717a" },
    typography: { fontFamily: "Inter", headingFamily: "Archivo", nameFamily: "Archivo", fontSize: 9.6, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.55, uppercaseHeadings: true },
    layout: { columns: 1 },
  },
  {
    id: "cv-aurum-cobalt",
    name: "Cobalt",
    source: "cv-aurum",
    description: "A bold cobalt banner and crisp tags. Modern and high-energy.",
    tags: ["single-column", "modern", "creative"],
    atsScore: 91,
    header: "banner",
    section: "bar",
    skills: "chips",
    sectionIcons: false,
    theme: { primary: "#1e40af", text: "#1f2937", muted: "#64748b" },
    typography: { fontFamily: "Mulish", headingFamily: "Mulish", nameFamily: "Mulish", fontSize: 9.6, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.45, uppercaseHeadings: true },
    layout: { columns: 1 },
  },
  {
    id: "cv-aurum-academia",
    name: "Academia",
    source: "cv-aurum",
    description: "A scholarly serif CV with room for publications. Built for academia.",
    tags: ["ats-safe", "single-column", "classic", "elegant"],
    atsScore: 96,
    header: "centered",
    section: "rule-after",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#374151", text: "#1f2933", muted: "#6b7280" },
    typography: { fontFamily: "Source Serif 4", headingFamily: "Source Serif 4", nameFamily: "Source Serif 4", fontSize: 9.7, lineHeight: 1.42, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: false },
    layout: { columns: 1, icons: false },
  },
  {
    id: "cv-aurum-verdant",
    name: "Verdant",
    source: "cv-aurum",
    description: "A calm green sidebar. Fresh, friendly, and easy to read.",
    tags: ["two-column", "modern", "minimal"],
    atsScore: 92,
    header: "standard",
    section: "plain",
    skills: "chips",
    sectionIcons: false,
    theme: { primary: "#047857", text: "#1f2933", muted: "#6b7280", sidebar: "#ecfdf5", sidebarText: "#065f46" },
    typography: { fontFamily: "Figtree", headingFamily: "Figtree", nameFamily: "Figtree", fontSize: 9.6, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.45, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "right", sidebarWidth: 0.33 },
  },
  {
    id: "cv-aurum-sienna",
    name: "Sienna",
    source: "cv-aurum",
    description: "Warm Spectral serif with terracotta accents. Editorial and inviting.",
    tags: ["single-column", "elegant", "creative"],
    atsScore: 93,
    header: "centered",
    section: "plain",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#b45309", text: "#292524", muted: "#78716c" },
    typography: { fontFamily: "Spectral", headingFamily: "Spectral", nameFamily: "Spectral", fontSize: 9.8, lineHeight: 1.44, letterSpacing: 0, headingScale: 1.6, uppercaseHeadings: true },
    layout: { columns: 1, icons: false, sectionGap: 11 },
  },
  {
    id: "cv-aurum-newton",
    name: "Newton",
    source: "cv-aurum",
    description: "A scholarly, LaTeX-style single column. Serif, centered, timeless.",
    tags: ["ats-safe", "single-column", "classic", "elegant"],
    atsScore: 96,
    header: "centered",
    section: "rule-after",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#334155", text: "#1e293b", muted: "#64748b" },
    typography: { fontFamily: "Source Serif 4", headingFamily: "Source Serif 4", nameFamily: "Source Serif 4", fontSize: 9.9, lineHeight: 1.36, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: false },
    layout: { columns: 1, icons: false },
  },
  {
    id: "cv-aurum-deedy",
    name: "Deedy",
    source: "cv-aurum",
    description: "The iconic two-column résumé — tight, bold, and recruiter-loved.",
    tags: ["two-column", "modern", "technical"],
    atsScore: 93,
    header: "standard",
    section: "plain",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#b03a2e", text: "#26211d", muted: "#6b6256", sidebar: "#faf7f2", sidebarText: "#3f372e" },
    typography: { fontFamily: "Lato", headingFamily: "Lato", nameFamily: "Lato", fontSize: 9.4, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.7, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "left", sidebarWidth: 0.3 },
  },
  {
    id: "cv-aurum-slate",
    name: "Slate",
    source: "cv-aurum",
    description: "Editorial gutter headings in cool teal. Quiet, confident, modern.",
    tags: ["single-column", "modern", "minimal"],
    atsScore: 94,
    header: "standard",
    section: "side",
    skills: "grouped-chips",
    sectionIcons: false,
    theme: { primary: "#0f766e", text: "#1f2937", muted: "#6b7280" },
    typography: { fontFamily: "DM Sans", headingFamily: "DM Sans", nameFamily: "DM Sans", fontSize: 9.6, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.5, uppercaseHeadings: true },
    layout: { columns: 1, sectionGap: 14 },
  },
  {
    id: "cv-aurum-mercury",
    name: "Mercury",
    source: "cv-aurum",
    description: "Corporate navy with Playfair headings. Executive and trustworthy.",
    tags: ["ats-safe", "single-column", "executive", "classic"],
    atsScore: 94,
    header: "split",
    section: "underline",
    skills: "inline",
    sectionIcons: true,
    theme: { primary: "#1e3a8a", text: "#1f2937", muted: "#64748b" },
    typography: { fontFamily: "Lato", headingFamily: "Playfair Display", nameFamily: "Playfair Display", fontSize: 9.6, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.6, uppercaseHeadings: true },
    layout: { columns: 1 },
  },
  {
    id: "cv-aurum-halcyon",
    name: "Halcyon",
    source: "cv-aurum",
    description: "A calm cyan sidebar with a photo. Friendly, fresh, easy to scan.",
    tags: ["two-column", "modern", "photo"],
    atsScore: 92,
    header: "standard",
    section: "plain",
    skills: "chips",
    sectionIcons: true,
    theme: { primary: "#0e7490", text: "#1f2937", muted: "#64748b", sidebar: "#ecfeff", sidebarText: "#155e63" },
    typography: { fontFamily: "Figtree", headingFamily: "Figtree", nameFamily: "Figtree", fontSize: 9.5, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.45, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "right", sidebarWidth: 0.33, showPhoto: true, photoShape: "circle", photoSize: "m" },
  },
  {
    id: "cv-aurum-graphite",
    name: "Graphite",
    source: "cv-aurum",
    description: "Monochrome ink with accent bars. Sharp, structured, engineer-ready.",
    tags: ["ats-safe", "single-column", "technical", "modern"],
    atsScore: 94,
    header: "standard",
    section: "bar",
    skills: "chips",
    sectionIcons: true,
    theme: { primary: "#111827", text: "#111827", muted: "#6b7280" },
    typography: { fontFamily: "IBM Plex Sans", headingFamily: "IBM Plex Sans", nameFamily: "IBM Plex Sans", fontSize: 9.5, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.45, uppercaseHeadings: true },
    layout: { columns: 1 },
  },
  {
    id: "cv-aurum-portrait",
    name: "Portrait",
    source: "cv-aurum",
    description: "Photo-forward with a deep sidebar. A personal, memorable first impression.",
    tags: ["two-column", "photo", "modern", "creative"],
    atsScore: 90,
    header: "standard",
    section: "plain",
    skills: "chips",
    sectionIcons: true,
    theme: { primary: "#0ea5e9", text: "#1f2937", muted: "#64748b", sidebar: "#0f172a", sidebarText: "#e2e8f0" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.4, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.45, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "left", sidebarWidth: 0.34, showPhoto: true, photoShape: "rounded", photoSize: "l" },
  },
  {
    id: "cv-aurum-spotlight",
    name: "Spotlight",
    source: "cv-aurum",
    description: "A bold color banner with your photo. Confident and contemporary.",
    tags: ["single-column", "creative", "photo", "modern"],
    atsScore: 89,
    header: "banner",
    section: "bar",
    skills: "chips",
    sectionIcons: true,
    theme: { primary: "#7c3aed", text: "#1f2937", muted: "#64748b" },
    typography: { fontFamily: "Poppins", headingFamily: "Poppins", nameFamily: "Poppins", fontSize: 9.5, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.4, uppercaseHeadings: true },
    layout: { columns: 1, showPhoto: true, photoShape: "circle", photoSize: "m" },
  },
  {
    id: "cv-aurum-mono",
    name: "Mono",
    source: "cv-aurum",
    description: "Stark black-on-white minimalism. Pure typography, zero noise.",
    tags: ["ats-safe", "single-column", "minimal"],
    atsScore: 95,
    header: "standard",
    section: "plain",
    skills: "inline",
    sectionIcons: false,
    theme: { primary: "#111111", text: "#111111", muted: "#777777" },
    typography: { fontFamily: "Inter", headingFamily: "Inter", nameFamily: "Inter", fontSize: 9.7, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.4, uppercaseHeadings: true },
    layout: { columns: 1, icons: false, sectionGap: 14 },
  },
  {
    id: "cv-aurum-opal",
    name: "Opal",
    source: "cv-aurum",
    description: "A soft pastel sidebar with a photo. Calm, polished, approachable.",
    tags: ["two-column", "photo", "modern", "elegant"],
    atsScore: 92,
    header: "standard",
    section: "plain",
    skills: "chips",
    sectionIcons: true,
    theme: { primary: "#7c3aed", text: "#27272a", muted: "#71717a", sidebar: "#f5f3ff", sidebarText: "#4c1d95" },
    typography: { fontFamily: "Work Sans", headingFamily: "Work Sans", nameFamily: "Work Sans", fontSize: 9.5, lineHeight: 1.4, letterSpacing: 0, headingScale: 1.45, uppercaseHeadings: true },
    layout: { columns: 2, sidebar: "left", sidebarWidth: 0.33, showPhoto: true, photoShape: "circle", photoSize: "m" },
  },
];
